### ISSUE TITLE
New icon ideas

### ISSUE THREAD

**Issue by commadelimited** [commadelimited/jQuery-Mobile-Icon-Pack#1]
Beer mug
Chain
Light bulb
Flame
Target
Shield
Key
Water drop

**Comment by commadelimited** [comment]
globe
camera (http://thenounproject.com/noun/camera/#icon-No476)
plane
full, half full, empty circles (http://thenounproject.com/noun/contrast/#icon-No546)
no symbol (http://thenounproject.com/noun/no/#icon-No558)
pie chart
eye (http://thenounproject.com/noun/eye/#icon-No421)
coffee (http://thenounproject.com/noun/coffee/#icon-No16)

**Comment by commadelimited** [comment]
http://www.entypo.com/

**Comment by commadelimited** [comment]
http://fortawesome.github.com/Font-Awesome/

**Comment by gercheq** [comment]
Great work! You might consider adding icons for:
- take photo (camera) 
- record video (camera)
- record audio (mic)
- type text (keyboard)

**Comment by commadelimited** [comment]
Thanks for your suggestion gercheq!

**Comment by linuxonrails** [comment]
Hey Andy! Font-awesome hasn't telephone icon.

Why Font-awesome has not all icons of Original-icons-pack? 

It would be wonderfull If only one sprite has all icons (basic + font-awesom-icons).
More simple and more efficient (only one image transfer).

Good work!!!

**Comment by linuxonrails** [comment]
back icon has the same problem: Font-awesome has no back icon.

http://jquerymobile.com/demos/1.1.0-rc.1/docs/buttons/buttons-icons.html

**Comment by matthewsheeran** [comment]
Yeah: needs a "reverse" to "play"!
Shall I get modify permissions, Git, check it out and add it: it is easy enough to revese the icon, add the CSS and bump all the others after it...

**Comment by halcyon1234** [comment]
![Uploading icon-group-white-18.png . . .]()
To complement the icon-user, how about icon-group (see attached-- or if I've messed up the attachment, imgur link below)
http://i.imgur.com/7IknU.png

**Comment by commadelimited** [comment]
@linuxonrails The primary reason I'm using multiple image sources is to keep backwards compatibility with the oiginal jQuery Mobile source. That way if people still want to keep using some of the original icons alongside Font Awesome icons they still can.

**Comment by commadelimited** [comment]
FYI. I'm going to close this ticket in favor of a new one. Some of the suggestions here have been implemented in Font Awesome
