### ISSUE TITLE
Navbar and Font awesome not working correctly

### ISSUE THREAD

**Issue by Koniak** [commadelimited/jQuery-Mobile-Icon-Pack#11]
When using the font awesome icons in a navbar it does not work correctly:
- The icons are placed so high above the text that its partly outside of the navbar button.
- data-iconpos does not work. The icon is always shown above the text. (and "notext" does not hide the text)

The problem has been replicated in Chrome and Firefox.

With the following code sample all icons are still displayed with text and icons above the text:

```
    <div data-role="footer" data-position="fixed" data-id="page-play-footer" id="page-play-footer" data-theme="e">
        <div data-role="navbar">
            <ul>
                <li><a id="btn-rew" href="#" data-icon="stop" data-iconpos="left">Back</a></li>             
                <li><a id="btn-play" href="#" data-icon="play" data-iconpos="notext">Play</a></li>
                <li><a href="#page-menu" data-icon="star" data-iconpos="notext" data-transition="slideup">more</a></li>                        
            </ul>    
        </div>
    </div>
```

**Comment by commadelimited** [comment]
@Koniak, do you have a page online where I can examine this issue?

**Comment by Koniak** [comment]
Hi, thanks for your quick response! I have now uploaded an example at:
http://fa.koniakowski.com.

**Comment by commadelimited** [comment]
@koniak...

Please start by upgrading to Icon Pack 2.1. Last week I released an update which included all of the original and extended icons plus the font awesome icons.

As for the positioning please switch to 2.1 and let's see if that's still a problem. I did some adjustments as well.

**Comment by Koniak** [comment]
Hi,

Updated to the latest Github version but it behaves exactly the same. I updated the uploaded example as well, so you can test your self.

**Comment by Koniak** [comment]
Hi Andy,

Have you had time to look at my example, which is using your latest (27/6) version?

**Comment by commadelimited** [comment]
It looks like the icons at the top display properly now.

As for your code, I can't duplicate your example locally. I've tried using jQuery Mobile 1.1.0 and the newly released 1.1.1. I've tried using both original icon pack and the fa icon pack.

**Comment by Koniak** [comment]
Updated to fa pack 2.1.2 and then the footer icons returned to the correct place. (The "original Icon pack" was always in the correct place)

Thank you Andy!

**Comment by Koniak** [comment]
Closing....

**Comment by commadelimited** [comment]
Great. Glad to help out.
