### ISSUE TITLE
Split lists layout bug

### ISSUE THREAD

**Issue by ghost** [commadelimited/jQuery-Mobile-Icon-Pack#13]
After integrating your updates into my app I found the following issue: Lists that have split icons do not show the icons correctly.

To re-create the bug, add this to your /font-awesome/index.html page:

```
                     <ul data-role="listview" data-theme="c" data-split-icon="road">
                        <li><a href="#">foo</a><a href="#">ok</a></li>
                     </ul>
```

You will see the icon is hiding off to the lower left hand of the circle.
I was able to fix my issue by commenting out line 18 of the fontawesome.css

**Comment by commadelimited** [comment]
@pweissbrod this issue is fixed in a release I pushed just now.
