### ISSUE TITLE
css updates

### ISSUE THREAD

**Issue by stevepeak** [commadelimited/jQuery-Mobile-Icon-Pack#17]
Fix for ui-navbar with icons not on top.
Fix for .ui-controlgroup-horizontal with buttons with data-iconpos="notext"

.ui-navbar[data-iconpos="top"] .ui-icon {
    margin-top: 0 !important;
}

.ui-controlgroup-horizontal .ui-btn-icon-notext{
    margin: 3px -1px 0 0 !important;
}
.ui-controlgroup-horizontal .ui-btn-icon-notext .ui-btn-inner .ui-icon{
    top: 0px;
    left: 0px;
}

**Comment by commadelimited** [comment]
Thanks Steve. Would you mind opening a pull request for this so that you can get credit?

**Comment by stevepeak** [comment]
I'm new to Github as you can see :) I hope I did this correctly. So I fork it and then make the changes?

Thanks! Your icon pack is great! I'm building some cool stuff over here if your interested in checking it out?

Best Regards

Steve Peak

**Comment by commadelimited** [comment]
Steve...you got it. Fork this project, make your changes, then submit a pull request.
