### ISSUE TITLE
"loading" dialog broken

### ISSUE THREAD

**Issue by DGuidi** [commadelimited/jQuery-Mobile-Icon-Pack#2]
referencing the icon pack css, the "loading" dialog that appears using $.mobile.showPageLoadingMsg() appears with a broken image

**Comment by DGuidi** [comment]
fixed put this code (from jqm 1.0.1 css) after ui-icon definition in jqm-icon-pack.css

.ui-icon-loading {
    background-image: url(images/ajax-loader.png);
    width: 40px;
    height: 40px;
    -moz-border-radius: 20px;
    -webkit-border-radius: 20px;
    border-radius: 20px;
    background-size: 35px 35px
}

**Comment by commadelimited** [comment]
Thanks Diego...this should be resolved now.

**Comment by DGuidi** [comment]
thanks :)

**Comment by DGuidi** [comment]
these are the settings to be used with 1.1.0 RC1
.ui-icon-loading {
    background: url(images/ajax-loader.gif);
    background-size: 46px 46px;
}

**Comment by commadelimited** [comment]
Great. Thank you again Diego.
