### ISSUE TITLE
Icons squished on iPhone and Android devices

### ISSUE THREAD

**Issue by hamx0r** [commadelimited/jQuery-Mobile-Icon-Pack#25]
I can test my mobile site in Chrome under Windows, Mac and Linux, and the Font Awesome icons look, well, awesome.  Once I pull up the same page in my mobile browser (the stock browser on Android or stock Safari on iPhone) the icons which are specifically non-stock jQuery Mobile look squished as if the browser is forcing 3 icons to take the space of 1. 

Screen shot <a href="https://plus.google.com/photos/116437155448662355536/albums/5800415975317489825/5800414736884207138?banner=pwa&authkey=CJrnuei909Wjag#photos/116437155448662355536/albums/5800415975317489825/5800414736884207138?banner=pwa&authkey=CJrnuei909Wjag">here<a>

You can see the site here: http://test.contracktor.com/mobile
Login with "411" for both the user and password.   You can see some of the icons look strange on mobile devices, but fine on desktop browsers.  I just (15 mins ago) updated to the latest FA icon pack.  

UPDATE 1: This problem only appears on mobile devices when trying to use jQuery Mobile icons with the FA icon pack installed.  If I  exclusively use FA icons, then they look fine.

UPDATE 2: The checkbox graphic for a normal input checkbox also looks squished when viewed on a mobile device.  It looks fine when viewing the mobile page on a desktop browsers.  One can recreate issue by commenting out the icon pack CSS then observe the checkbox inputs looking correct.  Using the URL and account above, one can click "Test Job" then the "Task"  then then "Edit Task" button.  The resulting page has a checkbox. 

UPDATE 3: Default listview icons also squished when viewed on mobile devices (the "cheveron-right" type icon for example).

**Comment by ghost** [comment]
Hi, hamx0r,

Did you ever find a workaround for this? I'm having the same trouble. 

Additional datapoint: this only happens if I'm using a theme created using the JQM ThemeRoller, not if I'm using the stock JQM theme. It looks like you're using a custom theme too.

**Comment by ghost** [comment]
Screenshots below:

Using standard theme:

http://games.contraterrene.com/screenshots/standard_theme.png

The home icon appears normal using the standard theme.

Using ThemeRoller theme: 

http://games.contraterrene.com/screenshots/custom_theme.png 

The home icon is squished to the top, and the wrench icon also appears. There are only two icons squeezed in on this screenshot, but some of the icons cause three to be displayed (just as shown on hamx0r's screenshot).

**Comment by hamx0r** [comment]
Hi There,

The workaround was to use the icon pack's name for the icon instead of the
JQM native name.  so insead of (im going based on memory here) icon-plus
youd use icon-fa-plus (for the Font Awesome pack).  the proble seems to
come from mixing names from different packs.  all of the native icons
appear to be in the FA pack under a different name.
hope that helps!
jason

**Comment by ghost** [comment]
Thanks! I'll give it a try.

**Comment by hamx0r** [comment]
Hi Tony

The workaround for me was to use the icon pack names for the native icons.
 I'm not by my code now, but if the normal JQM name was "icon-plus" and the
icon pack/font awesome name for the same looking icon is "icon-fa-add" then
use "icon-fa-add".  it seems all the native icons show up in the FA pack
under different names, and the weird icon squishing happens when trying to
use the native names instead of the FA names.

hope this helps!

jason

**Comment by ghost** [comment]
Seems to work fine. Thanks!

**Comment by hamx0r** [comment]
sure thing!  glad to help!

**Comment by trav-ma** [comment]
Great work around for the button icons but that doesn't fix the issue with the listview and check box icons. Does anyone have a more comprehensive fix for this?

**Comment by trav-ma** [comment]
Ah, there is an easy fix for this here.

http://stackoverflow.com/questions/14160716/jquery-mobile-icon-pack-squished-on-iphone

Simply make sure your FA Icon CSS file is declared after your custom theme.
