### ISSUE TITLE
ui-icon-forward

### ISSUE THREAD

**Issue by ghost** [commadelimited/jQuery-Mobile-Icon-Pack#26]
Ciao Andy,

I think there is a typo at row 237 on jqm-icon-pack-2.1.2-fa.css: 

.ui-icon-faforward:before              { content: "\f04e"; } 

should be

.ui-icon-forward:before              { content: "\f04e"; }

**Comment by matthewsheeran** [comment]
Na! Names are designed not to conflict with the original "forward" name in the original phongegap icon set hence "faforward" like the "fahome" I also found.

My problem is a different one: i am after a "play" icon e.g. '|>' flipped horizontally (or mirrored across a vertical centreline) as an "reverse" or "reverseplay" icon <|'.

Note that "reverse" is unused in all the namespaces but "reverseplay" might be better anyway forstalling any subsequent need for a "fa" prefix.

Be much appreciated and I think it is a much needed (by me anyway) missing icon!
