### ISSUE TITLE
Icon Pack not replacing jQuery Mobile's icons

### ISSUE THREAD

**Issue by stevevance** [commadelimited/jQuery-Mobile-Icon-Pack#27]
In my page I reference the jQuery Mobile (JQM) CSS file and then the Font Awesome (FA) Icon Pack CSS file. When the icon has the same name in JQM as in FA, the JQM version is used which fails to show the retina version. However, if I change the icon to a name only available in FA, the FA version is used and the retina version shows (when @media is matched, like in iPhone 5 simulator in Xcode). 

The way I understand it, FA is supposed to replace JQM icons, but this doesn't seem to be happening.

**Comment by commadelimited** [comment]
@stevevance do you have an example of this? To work properly the icon-pack CSS file needs to be included after the jquery mobile CSS file. Is this the case?

**Comment by stevevance** [comment]
I looked at all of the pages in my website and they all include FA CSS after jQueryMobile CSS. 

I never found a fix, but I worked my way around it by just creating new custom icons in jQueryMobile for the few that I needed. Since this happened two months ago, I don't fully remember the circumstances. I'm going to close this now and if it comes up again, I'll be back.

**Comment by commadelimited** [comment]
Great. Apologies again about the delay in responding to this.

**Comment by urbien** [comment]
I am also interested in completely replacing JQM icons with the icon font icons, so that it works in on retina and not retina displays. I also want to avoid downloading extra image file. 
@commadelimited is it possible to do that?
@stevevance can you share the definitions you added to FA css?

**Comment by commadelimited** [comment]
@Urbien...

To completely replace the original icons, you'd have to edit the framework's CSS file to remove the PNG request. Be  cautious about this because some of the icons used by jQuery Mobile can't be replaced in the standard way...the search icon for example.

**Comment by stevevance** [comment]
@urbien I added new icon definitions to my websites custom stylesheet. It looks like this:

```
.ui-icon-myapp-locateme {
    background: url("../mapicons/locateme_18x18.png") no-repeat rgba(0, 0, 0, 0.4)  !important;
    background-size: 18px 18px;
}
```

And the same icon for retina:

```

@media
only screen and (-webkit-min-device-pixel-ratio : 1.5),
only screen and (min-device-pixel-ratio : 1.5) {
    .ui-icon-myapp-locateme {
        background: url("../mapicons/locateme_36x36.png") no-repeat rgba(0, 0, 0, 0.4)  !important;
        background-size: 18px 18px;
    }
```

**Comment by urbien** [comment]
@commadelimited, @stevevance thank you for your replies, I will open an issue on jqm's github and see what they say.
