### ISSUE TITLE
Icons are shifted a little to the left.

### ISSUE THREAD

**Issue by WayneHiller** [commadelimited/jQuery-Mobile-Icon-Pack#29]
I am using the latest release 2.1.2 and all the icon images are shifted a little off center to the right of the circle. Any ideas what might be going on?

**Comment by commadelimited** [comment]
Wayne...

Do you have an example. I spent a good amount of time making sure the position of the icons was correct. Can you provide a little more information such as browser and browser version? A screenshot might also help.
