### ISSUE TITLE
jqm-icon-pack-1.1.1-fa.css has a invalid UTF-8 byte sequence

### ISSUE THREAD

**Issue by linuxonrails** [commadelimited/jQuery-Mobile-Icon-Pack#3]
I have the next problem with assets + jqm-icon-pack-1.1.1:

```
/home/davidm/Documentos/Devel/git/mobile/app/assets/stylesheets/jqm-icon-pack-1.1.1-fa.css has a invalid UTF-8 byte sequence
```

I have fixed with: 

```
iconv -f UTF-16 -t UTF-8 -o jqm-icon-pack-1.1.1-fa.FIXED.css jqm-icon-pack-1.1.1-fa.css
```

**Comment by commadelimited** [comment]
linuxonrails, would you mind issuing a pull request so that I can review?

**Comment by cmjnelson** [comment]
Thanks @linuxonrails. On a mac I did 

`iconv -f UTF-16 -t UTF-8 jqm-icon-pack-1.1.1-fa.css > jqm-icon-pack-1.1.1-fa.FIXED.css`

**Comment by linuxonrails** [comment]
done: You're asking commadelimited to pull 1 commit into commadelimited:master from linuxonrails:master

**Comment by commadelimited** [comment]
Hrm. It's not showing up as a pull request. Can you take another look please?

**Comment by linuxonrails** [comment]
I have other problem fixed in anoother commit: 

https://github.com/linuxonrails/jQuery-Mobile-Icon-Pack/commit/6ec2440d485a4e48abdfa40c20cb0e7dcecc1cf2

**Comment by linuxonrails** [comment]
FIXED
