### ISSUE TITLE
icon position in jquery mobile 1.3

### ISSUE THREAD

**Issue by leopittoni** [commadelimited/jQuery-Mobile-Icon-Pack#30]
Hi!
In jquery mobile 1.3 the normal icons of jquery mobile are shifted to the top, if I include the new css file...

**Comment by commadelimited** [comment]
Do you have an example? I spent a good amount of time making sure the position of the icons was correct. Can you provide a little more information such as browser and browser version? A screenshot might also help.

**Comment by sibartlett** [comment]
I can confirm that the alignment of all the normal icons is not correct when using jQuery Mobile 1.3, and I tested using Chrome and Firefox.

**Comment by sibartlett** [comment]
Looks like this icon pack needs to be updated - there are two new icons in jQuery Mobile 1.3.

**Comment by commadelimited** [comment]
Yep. Looks like an edit icon and a "list" icon, ala Facebook style side nav.

http://jquerymobile.com/demos/1.3.0-rc.1/css/themes/default/images/icons-36-black.png

**Comment by stevevance** [comment]
Screenshot of the issue.
![Screen Shot 2013-03-22 at 01 16 42 ](https://f.cloud.github.com/assets/1330459/289591/197f4f52-92b8-11e2-921a-2d3ef7566fbe.png)

**Comment by stevevance** [comment]
You can see the code here: http://bikechi.com/map.html

**Comment by commadelimited** [comment]
Just pushed the fix for this.
