### ISSUE TITLE
support for jquery mobile themes

### ISSUE THREAD

**Issue by urbien** [commadelimited/jQuery-Mobile-Icon-Pack#32]
icon color and background are hardcoded in fa css, I guess that is the default. What is the best way to apply the jqm theme colors for this icon pack?

**Comment by mayooresan** [comment]
I don't think those are hard coded themes. I can change the theme. See the example below

```
<a href="item.html" data-role="button" data-mini="true" data-inline="true" data-icon="th-list" data-theme="g">10</a>
```

![custom theme](https://f.cloud.github.com/assets/137518/279998/269354ba-9144-11e2-9e4b-90d18a0f6be6.PNG)

**Comment by commadelimited** [comment]
@urbien can you confirm what @mayooresan mentions?

**Comment by urbien** [comment]
investigating some more, will let you know today

**Comment by urbien** [comment]
after more testing it looks like themes work with font awesome. My bad. @mayooresan thanks for setting me straight. @commadelimited thank you for this work, we use it extensively in [Urbini](http://github.com/urbien/urbini), a mobile app builder for geeks-who-can't-code.

**Comment by commadelimited** [comment]
Right on! Super exciting. Glad you like them.
