### ISSUE TITLE
Nav bar icons are partially visible

### ISSUE THREAD

**Issue by mayooresan** [commadelimited/jQuery-Mobile-Icon-Pack#33]
When nav bar icons are set to the top they are partially visible when used Font Awesome Icon Pack Usage.

Please find the screen shot below.
![custom icon error](https://f.cloud.github.com/assets/137518/279989/89a9607c-9143-11e2-966e-3bfbc19e65ad.PNG)

other custom icons are looking OK for me.

Thanks for the great icons and hope there will be a fix for it.

**Comment by butchewing** [comment]
It seams to work as expected if you comment out margin-top: -10px !important; on .ui-icon

```
.ui-icon {
width: 20px;
height: 20px;
-moz-border-radius: 10px;
-webkit-border-radius: 10px;
border-radius: 10px;
/*margin-top: -10px !important;*/
line-height: 20px
}
```

**Comment by stevevance** [comment]
@butchewing That fixed this issue for me: https://github.com/commadelimited/jQuery-Mobile-Icon-Pack/issues/30

**Comment by commadelimited** [comment]
Just pushed the fix for this.
