### ISSUE TITLE
Fontawsome font doesn't show in Opera Mobile

### ISSUE THREAD

**Issue by RomaDotDev** [commadelimited/jQuery-Mobile-Icon-Pack#34]
Fontawsome custom font generated by your service works great in any Webkit browser and even in Firefox Mobile. Unfortunately the latest Opera Mobile (12.1) doesn't display fonts (tested on Android App and in Opera Emulator).

![fontawsomebug](https://f.cloud.github.com/assets/1380457/287093/7253ffa2-924e-11e2-8781-1f731bd98017.png)

However after I generated my own custom font using <a href="http://fontcustom.com/">Font Custom</a> generator I got fully working icons
![fontawsome](https://f.cloud.github.com/assets/1380457/287160/09b78fac-9250-11e2-8abe-fc60f70695af.png)

Looks like the solution is that fontcustom uses <a href="http://www.fontspring.com/blog/the-new-bulletproof-font-face-syntax">Bulletproof fontface</a> with svg file attached. 

P.S. Thank you for a great work!

**Comment by commadelimited** [comment]
@irsick, thanks for reporting this issue. I've applied the fix recommended in the article you linked:

http://jqmiconpack.andymatthews.net/
