### ISSUE TITLE
Default icon is not visible in jQuery Mobile 1.3 / Nexus 4

### ISSUE THREAD

**Issue by blueskyfish** [commadelimited/jQuery-Mobile-Icon-Pack#36]
Hello,
The default icon is not visible when displayed in the Nexus 4.
With remote debugging I can turn off the icons "images/icons-36-white-pack.png" then the icons are visible again.

**Comment by commadelimited** [comment]
Could you please provide a little more information, or perhaps some sample code which can be previewed? A JSFiddle would be ideal.
