### ISSUE TITLE
ui-icon-info not centered

### ISSUE THREAD

**Issue by barbalex** [commadelimited/jQuery-Mobile-Icon-Pack#39]
Hi and thanks for this great tool.

I changed your css like this:
.ui-icon-info { background-position: -540px -0; }
to
.ui-icon-info { background-position: -539px -0; }

This makes the info symbol nicely centered.

Cheers, Alex

**Comment by commadelimited** [comment]
@barbalex, can you post an example of what you're talking about please? I
