### ISSUE TITLE
BG Color Of Radio Buttons & Checkboxes

### ISSUE THREAD

**Issue by lwbrown** [commadelimited/jQuery-Mobile-Icon-Pack#40]
I am trying to figure out what is causing the RB and CB background color to be dark gray. On most of my screens I am using the default JQM color scheme instead of applying a data-theme. However if I apply a data-theme to either RB or CB the bg color is still dark gray.

Is there a style I am overlooking which causes the dark gray color? Thanks.

**Comment by commadelimited** [comment]
This was my fault. Issue #41 resolved the background color problem.
