### ISSUE TITLE
Some difference between css and scss.

### ISSUE THREAD

**Issue by Sheile** [commadelimited/jQuery-Mobile-Icon-Pack#42]
`jqm-icon-pack-3.0.0-fa.scss` contains patch by a0801c2cd2a3c4db778b8f57d49354d2dedc1ab5.
But, `jqm-icon-pack-3.0.0-fa.css` does NOT contain it.

As a result, `jqm-icon-pack-3.0.0-fa.css` has a problem to switch background-image with retina display.

Please recreate css file from scss.

**Comment by commadelimited** [comment]
Thanks for catching this @Sheile, I've rebuilt the CSS file in the most recent push.
