### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by leopd** [commadelimited/jQuery-Mobile-Icon-Pack#5]
This icon pack is really cool!  Can you please specify what license you're sharing it under?  MIT would be great.  :)

**Comment by commadelimited** [comment]
The license for the custom icons that I designed are DWTFYW :).

The font awesome icons are CC BY 3.0  (http://creativecommons.org/licenses/by/3.0/) according to their website:
http://fortawesome.github.com/Font-Awesome/ (at the bottom).

**Comment by leopd** [comment]
Awesome.  Thanks!
