### ISSUE TITLE
Some icons (e.g. "icon-plus", "icon-arrow-r") are displaced in firefox-mobile and chrome-mobile

### ISSUE THREAD

**Issue by SchulteDev** [commadelimited/jQuery-Mobile-Icon-Pack#51]
Hi,

using this theme I recognized some icons to be displaced in firefox-mobile[1] and chrome-mobile[2](Android 4.2.2). Default-Android-Browser and Safari on iPhone4 work fine.

It seems to me that only icons are displaced, which are already in jquery-mobile-default-icons. Displaced icons I see are: arrow-r, chat, plus, minus, radio-on.

The reason seems to be the overwriting of 
  .ui-icon:not(.ui-icon-loading),.ui-icon-searchfield:after {
    background: #666666;
    background: rgba(0, 0, 0, 0.4);
  }
in jqm-icon-pack-fa.css. Removing this entries fixes the displacement, but in this case the "icon-plus" is displayed beyond the icons from this icon-pack.

You can find my usecase on http://www.bestellbaer.de/app/guest/mobile/order/orderPoint.xhtml?orderPointId=6, just call this site with one of the mentioned browsers.

[1] Cant get any specific information from the app itself, installed is: https://play.google.com/store/apps/details?id=org.mozilla.firefox
[2] Chrome 28.0.1500.94, Webkit 537.16, JS V8 3.18.5.10

**Comment by commadelimited** [comment]
I took a look at your demo page in Chrome for iOS and it looks just like it does in Chrome for the desktop. Could you also provide a screenshot of the problem you're seeing?

**Comment by SchulteDev** [comment]
Crome-(Android-)Screenshosts are attached. Good to hear, that the problem does not occur on Chrome@iPhone

![screenshot_2013-07-23-07-19-56](https://f.cloud.github.com/assets/1948684/840016/4eec9134-f363-11e2-9ed4-e136b96d352e.png)
![screenshot_2013-07-23-07-20-51](https://f.cloud.github.com/assets/1948684/840017/4ee50ec8-f363-11e2-9a1b-a9a0128eef80.png)
![screenshot_2013-07-23-07-21-14](https://f.cloud.github.com/assets/1948684/840018/4f017072-f363-11e2-984f-738fed9b201f.png)

**Comment by SchulteDev** [comment]
Never mind.

I have watched your demo http://andymatthews.net/code/jQuery-Mobile-Icon-Pack/font-awesome/ in my android-chrome - this demo looks fine. So the problem has to be on my side.

**Comment by commadelimited** [comment]
It looks like your phone is identifying itself as high res and gets the media queries, but it doesn't understand the background-size attrbute.

**Comment by SchulteDev** [comment]
Hmmm, but that does not explain why your demo looks fine in my android-browser, but bestellbaer.de/6 does not, does it?!

Btw., media-queries in jqm-icon-pack-fa.css[1] are slightly different from those in jquery[2]

[1] 
@media only screen and (-webkit-min-device-pixel-ratio: 1.3),
        only screen and (-o-min-device-pixel-ratio: 3/2),
        only screen and (min--moz-device-pixel-ratio: 1.3),
        only screen and (min-device-pixel-ratio: 1.3),
        only screen and (min-resolution: 1.3dppx) {

[2] 
@media only screen and (-webkit-min-device-pixel-ratio:1.3),only screen and (min--moz-device-pixel-ratio:1.3),only screen and (min-resolution:200dpi){

from http://view.jquerymobile.com/1.3.2/dist/demos/css/themes/default/jquery.mobile.min.css

**Comment by rickygu** [comment]
I have the same problem browsing on android. It looks like everything in the fontawesome will work, but once font awesome is included, none of the default icons that came with jquery mobile works anymore.

**Comment by SchulteDev** [comment]
@rickygu Maybe you open up an own issue to have this problem discussed - my problem does still exist, too.
