### ISSUE TITLE
ui-icon-nodisc

### ISSUE THREAD

**Issue by mtamony** [commadelimited/jQuery-Mobile-Icon-Pack#52]
Is this not supported? When I add jqm-icon-pack-fa.css I have both disc and shadow with icon. When I remove it and use a standard icon I have no disc and no shadow.

Thanks.

**Comment by commadelimited** [comment]
@mtamony can you provide an example of what you mean?

**Comment by mtamony** [comment]
I just ended up making my own icons. I just can't seem to ever EASILY get rid of that stupid circle around JQM icons. I thought their implementation of ui-icon-nodisc was supposed to but it doesn't seem to do it.

**Comment by commadelimited** [comment]
Okay. Sorry that you had trouble.
