### ISSUE TITLE
jQuery Mobile 1.3.x support

### ISSUE THREAD

**Issue by alienlebarge** [commadelimited/jQuery-Mobile-Icon-Pack#53]
Latest version of [jQuery Mobile](http://jquerymobile.com/) is 1.3.x

Is there any plan/date to support officially this version ?
The [jQuery Mobile Icon Pack website](http://andymatthews.net/code/jQuery-Mobile-Icon-Pack/) mentione that it support only version 1.2.

![napkin 29 08 13 8 41 21 am](https://f.cloud.github.com/assets/611234/1047681/0723fd8a-1076-11e3-81ef-64e402ba32a3.png)

**Comment by commadelimited** [comment]
Hmm. Didn't realize that demo site was behind the times. I'll work on updating it this week.

**Comment by commadelimited** [comment]
@alienlebarge #54
