### ISSUE TITLE
Default jquery icons not working at jQuery-Mobile-Icon-Pack-demo for google-nexus, mobile-chrome & mobile-firefox

### ISSUE THREAD

**Issue by SchulteDev** [commadelimited/jQuery-Mobile-Icon-Pack#55]
Hi,

this issue is a new reporting of pull-request #51, but with more insights. For issue-description, please visit #51.

I have seen the pull-request #54. Because of this, it came to my mind, that in my project I am using jquery-mobile-1.3.x.

So I opened your demo again - and voola, in #51 described behaviour now affects the demo, too. Screenshot is attached. See "Back" button in the header.

![screenshot_2013-09-17-11-35-56](https://f.cloud.github.com/assets/1948684/1156159/fc7e4a98-1f7f-11e3-997b-006f374ed191.png)

**Comment by Fyb3roptik** [comment]
I am seeing this issue too

**Comment by ywehrli** [comment]
me too, especially with the radio buttons

**Comment by jawa-the-hutt** [comment]
FWIW, I'm seeing this same issue on my iPhone 5 running IOS 7.0.  However, I'm not seeing it on the following devices:
1.  iPhone 3GS running IOS 6.1.3
2.  iPhone 4 running IOS 6.1.3
3.  iPad 3 running IOS 5.1.1   <---  I updated this device this morning to IOS 7.0 and the issue can be reproduced on it.

**Comment by rickygu** [comment]
having the same problem.

**Comment by andreasfleck** [comment]
I adding !important for each background-size where background-image is set to icons-36-pack.png:
In jqm-icon-pack-fa.css
search for:
 background-image:url("images/icons-36-white-pack.png") !important;
and set:
 -moz-background-size:774px 54px !important;-o-background-size:774px 54px !important;-webkit-background-size:774px 54px !important;background-size:774px 54px !important

Hope this helps!

**Comment by ebonato** [comment]
Great fix @andreasfleck !!
Works like a charm!! 
Tested on IOS 7.0.2 Safari and mobile-chrome.
jQuery 1.9.1, jQM 1.3.2

**Comment by jawa-the-hutt** [comment]
Works for me on all of my previously mentioned devices/IOS versions.

Thanks for the fix @andreasfleck

**Comment by lalaina** [comment]
Works on Mobile Chrome ! 

Thanks

**Comment by juddlyon** [comment]
@andreasfleck is a gentleman and a scholar. 

Fixed the issue in iOS 7, didn't test elsewhere.
jQuery 1.10.2, JQM 1.3.2

**Comment by commadelimited** [comment]
#61 should make these issues irrelevant. Feel free to test now. Release happens soon.
