### ISSUE TITLE
Not working with jQueryMobile 1.4.0

### ISSUE THREAD

**Issue by gercheq** [commadelimited/jQuery-Mobile-Icon-Pack#56]
I think buttons lost their extra markup so icons are not working anymore with the latest jQueryMobile 1.4.0

**Comment by commadelimited** [comment]
jQuery Mobile 1.4 is still in beta. I have not yet tested any of my projects with 1.4, but as soon as it's released I'll get on it.

**Comment by m-vdv** [comment]
1.4 has been available for a couple of days, please update the icon pack :+1:

**Comment by frankabbruzzese** [comment]
Please update the icon-pack to jquery mobile 1.4 :+1:

**Comment by gasparitiago** [comment]
Please update the icon-pack to jquery mobile 1.4 :+1:

**Comment by commadelimited** [comment]
The update for this is in progress.

**Comment by m-vdv** [comment]
Great news! Thanks Andy :smile:

**Comment by commadelimited** [comment]
#61 is coming soon.
