### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by codinguncut** [commadelimited/jQuery-Mobile-Icon-Pack#59]
Your git clone command in the Readme `git clone git@github.com:commadelimited/jQuery-Mobile-Icon-Pack.git` didn't work for me:

<pre>
Warning: Permanently added the RSA host key for IP address '192.30.252.129' to the list of known hosts.
Permission denied (publickey).
fatal: The remote end hung up unexpectedly
</pre>

Using the standard `git clone https://github.com/commadelimited/jQuery-Mobile-Icon-Pack.git` did work instead.

**Comment by commadelimited** [comment]
Hah. Good catch. Fixed in #61.
