### ISSUE TITLE
data-iconpos="notext"

### ISSUE THREAD

**Issue by tegansnyder** [commadelimited/jQuery-Mobile-Icon-Pack#6]
Adding this to a button appears to place a -10px margin on the icon resulting in a off center icon.

**Comment by commadelimited** [comment]
Tegan..were you using original or font awesome icons?

**Comment by commadelimited** [comment]
Never mind. I see that it's only happening in the Font awesome icons.

**Comment by commadelimited** [comment]
This is fixed now Tegan.

**Comment by tegansnyder** [comment]
awesome thanks Andy

**Comment by seba229** [comment]
Hey! I just found out that your fix for issue #6 leads to problems with buttons in horizontal control groups:

![buttons](https://f.cloud.github.com/assets/3371430/94032/8b79db8c-663e-11e2-8a8d-69afffd99a4a.jpg)

If I remove this part from the css file, the icons are shown correctly:

.ui-btn-icon-notext .ui-btn-inner .ui-icon {
    margin: 1px 1px 2px 2px !important;
}

**Comment by geiregjo** [comment]
I have the same issue that seba229 has. The css selector is not strict enought I think.

**Comment by jawa-the-hutt** [comment]
I have the same issue as seba229 and geiregjo.  the icons all appear in the lower left corner of the button.

I have just commented out the line in the css file for the time being.

**Comment by alirizakeles** [comment]
Yes I have the same. It seems this fix causes new problem.
