### ISSUE TITLE
Icons slightly displaced on Chrome v32 (JQM 1.4)

### ISSUE THREAD

**Issue by saulojg** [commadelimited/jQuery-Mobile-Icon-Pack#64]
Please see image below

![Example](https://dl.dropboxusercontent.com/u/6434162/jqm-icons-01.png)

**Comment by commadelimited** [comment]
@mand1nga I noticed that while I was putting the icons together. I've decided for now to leave it as is. Positioning the icons is a huge pain as I have to do each of them one at a time. Plus given that different people use them differently, no one person's configuration would match up with my test data.
