### ISSUE TITLE
Icons displayed in the wrong color when using the builder

### ISSUE THREAD

**Issue by nicolasgrolleau** [commadelimited/jQuery-Mobile-Icon-Pack#65]
When I use the builder to have a smaller icon pack, the icons are displayed in black instead of white, which make them nearly invisible with jquerymobile 1.4 theme b.

Everything is ok when using the full pack.

This issue is visible also in the index.html generated in the custom icon pack. (more visible after adding data-theme="b" to a anchor line)

**Comment by commadelimited** [comment]
Changed the default color of the downloaded icons to white in [55d64ae](https://github.com/commadelimited/jQuery-Mobile-Icon-Pack-Builder/commit/a9dbde2bcbdc1301647aee72d57fbbf33b5e4a8b).
