### ISSUE TITLE
Icons are off center

### ISSUE THREAD

**Issue by dnrce** [commadelimited/jQuery-Mobile-Icon-Pack#69]
Many icons are positioned slightly to the left of center. This is visible when viewing the demo page in Chrome and Firefox on Windows 7.

**Comment by commadelimited** [comment]
This is the same as #68. For the time being I'm intentionally not doing this work.

**Comment by dnrce** [comment]
Whoops, sorry for the dupe.

**Comment by commadelimited** [comment]
No worries at all. There's just so many icons and they might still be off center in someone's implementation.
