### ISSUE TITLE
Do my checkboxes look funny to you?

### ISSUE THREAD

**Issue by ghost** [commadelimited/jQuery-Mobile-Icon-Pack#7]
Notice how I dont see a check mark in the box. Am I doing it wrong?
unchecked:
![unchecked](http://reallifedata.com/Transfer/1.png)
checked
![checked](http://reallifedata.com/Transfer/2.png)

**Comment by commadelimited** [comment]
Pete. Looks like an offset bug. I'll get this fixed in a revision coming soon.

**Comment by ghost** [comment]
Thanks Andy!
I've been making an app that hits many of the different features of
jqmobile and I must say everything except the checkboxes look dead on
perfect.
Coming from a data programmer (who is far from an expert in css) your
contribution has been a huge help in my project and I do hope that jquery
mobile folds your work in to their releases.

On 22 May 2012 16:50, Andy Matthews <
reply@reply.github.com

> wrote:
> 
> Pete. Looks like an offset bug. I'll get this fixed in a revision coming
> soon.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/commadelimited/jQuery-Mobile-Icon-Pack/issues/7#issuecomment-5858527

## 

Peter Weissbrod
Founder and Engineer
http://RealLifeData.com | O: 207.439.3489 | M: 406.531.1263

**Comment by commadelimited** [comment]
Pete...

I took a look at the icon source and it works fine for me. I also added a checkbox and radio button sample to my demo page for the original icons, please take a look and confirm you're using the same code.

If that doesn't solve it, could you please post a snippet of your code that illustrates the problem and I'll see if I can figure out what it might be.

**Comment by commadelimited** [comment]
Btw, I updated the icon images as I didn't realize they weren't transparent like the new 1.1 icons from jQuery Mobile code.
