### ISSUE TITLE
Icons not centered

### ISSUE THREAD

**Issue by HStokbro** [commadelimited/jQuery-Mobile-Icon-Pack#71]
The icons are built, so they er placed left in the 16 x 16 pixels. This goes for both png and svg. They should be centered.

Check out "angle-right" on this page: 
http://andymatthews.net/code/jQuery-Mobile-Icon-Pack/

**Comment by commadelimited** [comment]
@HStokbro Yes. I'm aware of the centering issues. For the time being I'm leaving it as is. Please see the updated readme concerning [centered icons](https://github.com/commadelimited/jQuery-Mobile-Icon-Pack#centered-icons).

**Comment by andrzejpolis** [comment]
Really? I cannot believe this can be left as it is... This makes this project unusable. Half of this icons look like crap. That is really sad. Whole idea is really great. Hope someone will make an effort to fix it someday.

**Comment by commadelimited** [comment]
1) pull requests are always welcome.
2) it's highly unlikely that the centering will be correct for every use case. That means that you'll likely be adjusting the centering for your implementation. Why spend time changing something that you'll also have to change?
