### ISSUE TITLE
font-awesome show a Plus sign

### ISSUE THREAD

**Issue by menex** [commadelimited/jQuery-Mobile-Icon-Pack#9]
Just downloaded the Icon pack but all the font-awesome fonts shows a plus sign

**Comment by commadelimited** [comment]
@menex you're gonna have to give me more to go on than that.

Is this hosted online or on your local machine?
Are you getting any errors in console when you first load the page?
Are you making sure the path to the CSS file is correct, and to the font files themselves?

**Comment by commadelimited** [comment]
Menex...

It looks like I made a mistake in /font-awesome/index.html.

I updated the version of the CSS file, but forgot to update the reference to that file in index.html.

Please change this line:
`<link rel="stylesheet" href="jqm-icon-pack-1.1.1-fa.css" />`

to this
`<link rel="stylesheet" href="jqm-icon-pack-1.1.2-fa.css" />`

**Comment by commadelimited** [comment]
By the way, I'm going to be releasing an update to Icon Pack today, and this will be fixed in it. You're welcome to wait.

**Comment by menex** [comment]
Great got it working thanks for the support.

**Comment by commadelimited** [comment]
My pleasure Menex.

I just pushed the update to Icon Pack. 70 new icons and a few minor fixes for the original icons.

**Comment by menex** [comment]
Thanks They look Great. Keep it up Man.
